mutation CreateClass($tableId: ID!, $title: String!, $shift: Int!) {
  createClass(title: $title, tableId: $tableId, shift: $shift) {
    id
    title
    shift
  }
}

mutation UpdateClass($tableId: ID!, $title: String!, $id: ID!, $shift: Int!) {
  updateClass(title: $title, id: $id, tableId: $tableId, shift: $shift) {
    id
    title
    shift
  }
}

mutation DeleteClass($id: ID!, $tableId: ID!) {
  deleteClass(id: $id, tableId: $tableId) {
    id
  }
}

query GetClasses($tableId: ID!) {
  classes(tableId: $tableId) {
    id
    title
    shift
  }
}
