mutation CreateClass(
  $tableId: ID!
  $number: Int!
  $sector: String!
  $letter: String!
  $shift: Int!
) {
  createClass(
    number: $number
    sector: $sector
    letter: $letter
    tableId: $tableId
    shift: $shift
  ) {
    id
    number
    sector
    letter
    tableId
    shift
  }
}

mutation UpdateClass(
  $tableId: ID!
  $number: Int!
  $sector: String!
  $letter: String!
  $shift: Int!
) {
  updateClass(
    number: $number
    sector: $sector
    letter: $letter
    tableId: $tableId
    shift: $shift
  ) {
    id
    number
    sector
    letter
    tableId
    shift
  }
}

mutation DeleteClass($id: ID!, $tableId: ID!) {
  deleteClass(id: $id, tableId: $tableId) {
    id
  }
}

query GetClasses($tableId: ID!) {
  classes(tableId: $tableId) {
    id
    shift
    number
    letter
    sector
  }
}
