mutation CreateSubject($tableId: ID!, $title: String!) {
  createSubject(title: $title, tableId: $tableId) {
    id
    title
  }
}

mutation UpdateSubject($tableId: ID!, $title: String!, $id: ID!) {
  updateSubject(title: $title, id: $id, tableId: $tableId) {
    id
    title
  }
}

mutation DeleteSubject($id: ID!, $tableId: ID!) {
  deleteSubject(id: $id, tableId: $tableId) {
    id
  }
}

query GetSubjects {
  subjects {
    id
    title {
      ru
    }
  }
}
