mutation CreateTable($title: String!, $slug: String!) {
  createTable(title: $title, slug: $slug) {
    id
    slug
    title
    created
    lastModified
  }
}

mutation UpdateTable($title: String!, $slug: String!, $id: ID!) {
  updateTable(title: $title, slug: $slug, id: $id) {
    id
    slug
    title
    created
    lastModified
  }
}

mutation DeleteTable($id: ID!) {
  deleteTable(id: $id) {
    id
  }
}

mutation DuplicateTable($id: ID!) {
  duplicateTable(id: $id) {
    id
  }
}

query GetTable($slug: String!) {
  table(slug: $slug) {
    id
    title
    created
    # subjects {
    #   id
    #   title
    # }
    classes {
      id
      number
      letter
      sector
      shift
    }
    teachers {
      id
      name
      slug
      # workloadAmount
      workload {
        subjectId
        classId
        hours
      }
      workhours
    }
    lastModified
  }
}
