mutation CreateTeacher($tableId: ID!, $name: String!, $slug: String!) {
  createTeacher(tableId: $tableId, name: $name, slug: $slug) {
    id
    name
    slug
  }
}

mutation UpdateTeacher(
  $id: ID!
  $tableId: ID!
  $name: String!
  $slug: String!
) {
  updateTeacher(id: $id, tableId: $tableId, name: $name, slug: $slug) {
    id
    tableId
    name
    slug
  }
}

mutation DeleteTeacher($id: ID!, $tableId: ID!) {
  deleteTeacher(id: $id, tableId: $tableId) {
    id
  }
}

mutation UpdateWorkload(
  $tableId: ID!
  $teacherId: ID!
  $subjectId: ID!
  $classId: ID!
  $hours: Int!
) {
  updateWorkload(
    tableId: $tableId
    teacherId: $teacherId
    subjectId: $subjectId
    classId: $classId
    hours: $hours
  ) {
    subjectId
    classId
    hours
  }
}

mutation UpdateWorkhour(
  $tableId: ID!
  $teacherId: ID!
  $day: String!
  $hour: String!
  $value: Boolean!
) {
  updateWorkhour(
    tableId: $tableId
    teacherId: $teacherId
    day: $day
    hour: $hour
    value: $value
  ) {
    day
    hour
    value
  }
}

query GetTeachers($tableId: ID!) {
  teachers(tableId: $tableId) {
    id
    name
    # workloadAmount
    workload {
      subjectId
      classId
      hours
    }
    workhours
    slug
  }
}

query GetTeacher($tableId: ID!, $slug: String!) {
  teacher(tableId: $tableId, slug: $slug) {
    id
    name
    workload {
      subjectId
      classId
      hours
    }
    workhours
    slug
  }
}
