mutation SignIn($username: String!, $password: String!) {
  signIn(username: $username, password: $password) {
    token
  }
}

query GetUser {
  user {
    name
    tables {
      id
      slug
      created
      lastModified
      title
    }
  }
}
